name: "Publish to Github Pages"

on: [push, pull_request]

jobs:
  cd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run predeploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist

      - name: Create CNAME file
        run: |
          touch CNAME
          echo daisy.js.org >> CNAME
          cat CNAME
      - name: Commit CNAME file
        uses: EndBug/add-and-commit@v7
        with:
          add: 'CNAME'
          branch: gh-pages

